### ISSUE TITLE
Display function is not working

### ISSUE THREAD

**Issue by lincolnfrias** [tylere/jupyter_widget_gmaps#1]
First, thanks for sharing this.

But nothing happens after `display(map1)`.

Not sure if it is related, but I'm getting this message after executing the python half of the widget:

    /home/lincoln/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:6: DeprecationWarning:  metadata {'sync': True} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')

Do you have any thoughts on how to get `display( )` to work again?

**Comment by tylere** [comment]
I'm afraid that I haven't kept this example up to date with changes to the Jupyter/IPython codebases. If you are an experienced Python programmer, I would suggest starting by looking at what changed with traitlets 4.1 (as indicated by the error message).

**Comment by lincolnfrias** [comment]
Thanks for the fast answer, @tylere. I am not an experienced programmer at all, but I will try to update it in the next days.

**Comment by lincolnfrias** [comment]
Great news, somebody made a [similar installable widget](https://github.com/pbugnion/gmaps).
